// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetAPIKey(arg1) {
    return window['go']['linear']['Manager']['SetAPIKey'](arg1);
}

export function GetMe() {
    return window['go']['linear']['Manager']['GetMe']();
}

export function ListTeams() {
    return window['go']['linear']['Manager']['ListTeams']();
}

export function GetCycleIssues(arg1) {
    return window['go']['linear']['Manager']['GetCycleIssues'](arg1);
}

export function GetIssue(arg1) {
    return window['go']['linear']['Manager']['GetIssue'](arg1);
}

export function UpdateIssueState(arg1, arg2) {
    return window['go']['linear']['Manager']['UpdateIssueState'](arg1, arg2);
}

export function StartPolling(arg1, arg2) {
    return window['go']['linear']['Manager']['StartPolling'](arg1, arg2);
}

export function StopPolling() {
    return window['go']['linear']['Manager']['StopPolling']();
}

export function IsConnected() {
    return window['go']['linear']['Manager']['IsConnected']();
}

export function LoadAPIKey(arg1) {
    return window['go']['linear']['Manager']['LoadAPIKey'](arg1);
}

export function PrepareWorkspace(arg1, arg2) {
    return window['go']['linear']['Manager']['PrepareWorkspace'](arg1, arg2);
}

export function ListRepoDirectories(arg1) {
    return window['go']['linear']['Manager']['ListRepoDirectories'](arg1);
}

export function DetectReposPrompt(arg1, arg2, arg3) {
    return window['go']['linear']['Manager']['DetectReposPrompt'](arg1, arg2, arg3);
}

export function GetMyIssues() {
    return window['go']['linear']['Manager']['GetMyIssues']();
}

export function StartMyIssuesPolling(arg1) {
    return window['go']['linear']['Manager']['StartMyIssuesPolling'](arg1);
}

export function StartOAuth(arg1) {
    return window['go']['linear']['Manager']['StartOAuth'](arg1);
}

export function CancelOAuth() {
    return window['go']['linear']['Manager']['CancelOAuth']();
}

export function Disconnect() {
    return window['go']['linear']['Manager']['Disconnect']();
}

export function LoadOAuthToken(arg1) {
    return window['go']['linear']['Manager']['LoadOAuthToken'](arg1);
}
