// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Team {
  id: string;
  name: string;
  key: string;
}

export interface Cycle {
  id: string;
  name: string;
  number: number;
  startsAt: string;
  endsAt: string;
}

export interface Issue {
  id: string;
  identifier: string;
  title: string;
  description: string;
  priority: number;
  state: State;
  assignee: User | null;
  labels: Label[];
  team: Team | null;
  url: string;
  createdAt: string;
  updatedAt: string;
}

export interface State {
  id: string;
  name: string;
  color: string;
  type: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
}

export interface Label {
  id: string;
  name: string;
  color: string;
}

export interface Me {
  id: string;
  name: string;
  email: string;
}

export interface CycleIssuesResponse {
  cycle: Cycle | null;
  issues: Issue[];
  states: State[];
}

export function SetAPIKey(key: string): Promise<Me>;
export function GetMe(): Promise<Me>;
export function ListTeams(): Promise<Team[]>;
export function GetCycleIssues(teamID: string): Promise<CycleIssuesResponse>;
export function GetIssue(issueID: string): Promise<Issue>;
export function UpdateIssueState(issueID: string, stateID: string): Promise<void>;
export function StartPolling(teamID: string, intervalSec: number): Promise<void>;
export function StopPolling(): Promise<void>;
export function IsConnected(): Promise<boolean>;
export function LoadAPIKey(key: string): Promise<void>;
export function PrepareWorkspace(issueIdentifier: string, baseDir: string): Promise<string>;
export function ListRepoDirectories(baseDir: string): Promise<string[]>;
export function DetectReposPrompt(issueTitle: string, issueDescription: string, repos: string[]): Promise<string>;
export function GetMyIssues(): Promise<CycleIssuesResponse>;
export function StartMyIssuesPolling(intervalSec: number): Promise<void>;
export function StartOAuth(clientID: string): Promise<void>;
export function CancelOAuth(): Promise<void>;
export function Disconnect(): Promise<void>;
export function LoadOAuthToken(token: string): Promise<void>;
