// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SessionConfig {
  name: string;
  agent: string;
  directory: string;
  useWorktree: boolean;
  worktreePath: string;
  branch: string;
}

export interface SessionState {
  id: string;
  name: string;
  agent: string;
  directory: string;
  worktreePath: string;
  branch: string;
  status: string;
}

export function CreateSession(config: SessionConfig): Promise<string>;
export function WriteToSession(id: string, data: string): Promise<void>;
export function ResizeSession(id: string, cols: number, rows: number): Promise<void>;
export function CloseSession(id: string): Promise<void>;
export function ListSessions(): Promise<SessionState[]>;
export function GetSessionLog(id: string): Promise<string>;
export function ResumeSession(id: string): Promise<void>;
