// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {linear} from '../models';
import {context} from '../models';

export function CancelOAuth():Promise<void>;

export function DetectReposPrompt(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function Disconnect():Promise<void>;

export function GetCycleIssues(arg1:string):Promise<linear.CycleIssuesResponse>;

export function GetIssue(arg1:string):Promise<linear.Issue>;

export function GetMe():Promise<linear.Me>;

export function GetMyIssues():Promise<linear.CycleIssuesResponse>;

export function IsConnected():Promise<boolean>;

export function ListRepoDirectories(arg1:string):Promise<Array<string>>;

export function ListTeams():Promise<Array<linear.Team>>;

export function LoadAPIKey(arg1:string):Promise<void>;

export function LoadOAuthToken(arg1:string):Promise<void>;

export function PrepareWorkspace(arg1:string,arg2:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<linear.Me>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartMyIssuesPolling(arg1:number):Promise<void>;

export function StartOAuth(arg1:string):Promise<void>;

export function StartPolling(arg1:string,arg2:number):Promise<void>;

export function StopPolling():Promise<void>;

export function UpdateIssueState(arg1:string,arg2:string):Promise<void>;

export function ValidateAPIKey(arg1:string):Promise<linear.Me>;
