// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {context} from '../models';

export function AddWorkspace(arg1:workspace.AddWorkspaceConfig):Promise<string>;

export function CloneAndAddWorkspace(arg1:workspace.AddWorkspaceConfig):Promise<string>;

export function CloneDestPreview(arg1:string,arg2:string):Promise<string>;

export function ListWorkspaces():Promise<Array<workspace.WorkspaceWithSessions>>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
