// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['session']['Manager']['CloseSession'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['session']['Manager']['CreateSession'](arg1);
}

export function GetSessionLog(arg1) {
  return window['go']['session']['Manager']['GetSessionLog'](arg1);
}

export function ListSessions() {
  return window['go']['session']['Manager']['ListSessions']();
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['session']['Manager']['ResizeSession'](arg1, arg2, arg3);
}

export function ResumeSession(arg1) {
  return window['go']['session']['Manager']['ResumeSession'](arg1);
}

export function SetContext(arg1) {
  return window['go']['session']['Manager']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['session']['Manager']['Shutdown']();
}

export function WriteToSession(arg1, arg2) {
  return window['go']['session']['Manager']['WriteToSession'](arg1, arg2);
}
