// @ts-check
// This file is automatically generated. DO NOT EDIT

export function AddWorkspace(arg1) {
    return window['go']['workspace']['Manager']['AddWorkspace'](arg1);
}

export function CloneAndAddWorkspace(arg1) {
    return window['go']['workspace']['Manager']['CloneAndAddWorkspace'](arg1);
}

export function ListWorkspaces() {
    return window['go']['workspace']['Manager']['ListWorkspaces']();
}

export function RemoveWorkspace(arg1) {
    return window['go']['workspace']['Manager']['RemoveWorkspace'](arg1);
}

export function CloneDestPreview(arg1, arg2) {
    return window['go']['workspace']['Manager']['CloneDestPreview'](arg1, arg2);
}
