// This file is automatically generated. DO NOT EDIT

import type { SessionState } from '../session/Manager';

export interface Workspace {
  id: string;
  name: string;
  path: string;
  agent: string;
  cloned: boolean;
}

export interface WorkspaceWithSessions extends Workspace {
  sessions: SessionState[];
}

export interface AddWorkspaceConfig {
  path?: string;
  repoUrl?: string;
  reposBaseDir?: string;
  name?: string;
  agent?: string;
}

export function AddWorkspace(config: AddWorkspaceConfig): Promise<string>;
export function CloneAndAddWorkspace(config: AddWorkspaceConfig): Promise<string>;
export function ListWorkspaces(): Promise<WorkspaceWithSessions[]>;
export function RemoveWorkspace(id: string): Promise<void>;
export function CloneDestPreview(repoURL: string, reposBaseDir: string): Promise<string>;
