// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardData() {
  return window['go']['agent']['Tracker']['GetDashboardData']();
}

export function SetContext(arg1) {
  return window['go']['agent']['Tracker']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['agent']['Tracker']['Shutdown']();
}
