// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {context} from '../models';

export function GetDashboardData():Promise<agent.DashboardData>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;
