// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SessionMetrics {
  sessionId: string;
  sessionName: string;
  agent: string;
  status: string;
  thinkingTime: number;
  waitingTime: number;
  idleTime: number;
  totalTime: number;
  lastActivity: string;
  isStuck: boolean;
}

export interface MetricSnapshot {
  timestamp: string;
  activeCount: number;
  thinkingCount: number;
  waitingCount: number;
  idleCount: number;
}

export interface DashboardData {
  sessions: SessionMetrics[];
  history: MetricSnapshot[];
  stuckAgents: SessionMetrics[];
}

export function GetDashboardData(): Promise<DashboardData>;
