// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneDestPath(arg1, arg2) {
  return window['go']['worktree']['Manager']['CloneDestPath'](arg1, arg2);
}

export function CloneRepo(arg1, arg2) {
  return window['go']['worktree']['Manager']['CloneRepo'](arg1, arg2);
}

export function CreateWorktree(arg1, arg2) {
  return window['go']['worktree']['Manager']['CreateWorktree'](arg1, arg2);
}

export function IsGitRepo(arg1) {
  return window['go']['worktree']['Manager']['IsGitRepo'](arg1);
}

export function ListWorktrees(arg1) {
  return window['go']['worktree']['Manager']['ListWorktrees'](arg1);
}

export function ParseRepoURL(arg1) {
  return window['go']['worktree']['Manager']['ParseRepoURL'](arg1);
}

export function RemoveWorktree(arg1, arg2) {
  return window['go']['worktree']['Manager']['RemoveWorktree'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['worktree']['Manager']['SetContext'](arg1);
}
