// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Settings {
  defaultAgent: string;
  defaultWorktree: boolean;
  theme: string;
  shellPath: string;
  reposBaseDir: string;
  archiveWorktreeCleanupDays: number;
}

export function GetSettings(): Promise<Settings>;
export function SaveSettings(settings: Settings): Promise<void>;
